name: Copy into another repo (dev)

on:
  pull_request:
    types: [closed]
    branches: [develop] # feature/** -> develop으로 병합 요청(PR) 시

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      # - name: creates output
      #   run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PRIVATE_REPO_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: ${{ secrets.PRIVATE_REPO_USERNAME }}
          destination-repository-name: ${{ secrets.PRIVATE_REPO_NAME }}
          user-email: ${{ secrets.PRIVATE_REPO_EMAIL }}
          target-branch: develop
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
